[package]
name = "fromenv"
version = "0.1.0"
edition = "2024"

[dependencies]
fromenv-derive = { path = "../fromenv-derive" }

[dev-dependencies]
insta = "1.43.1"
temp-env = "0.3.6"
secrecy = "0.10.3"
