[package]
name = "config-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
darling = "0.21.1"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["parsing", "derive"] }
